### ISSUE TITLE
SimpHook does not work as expected

### ISSUE THREAD

**Issue by caphindsight** [tririver/MathGR#4]
Hi!

It appears that `SimpHook` does not work properly. It is only respected when the name of the index is the same as in the definition of the hook. Or am I using it wrong?

![screenshot from 2016-03-18 16-55-02](https://cloud.githubusercontent.com/assets/10833413/13879779/b0cd5250-ed32-11e5-982e-cd163b2397b7.png)

**Comment by tririver** [comment]
Hi, caphindsight,

Note that `MathGR` is a package which built upon the general principles of Mathematica. `SimpHook` is nothing but a set of replacement rules. So if you'd like to do general replacement, you should do

`SimpHook = {A[DN[a_]] :> B[DN[a]]}`

Then it will work as desired.

Cheers,
Yi

**Comment by caphindsight** [comment]
Thanks!

**Comment by caphindsight** [comment]
Hi again!
Sorry if I am bothering you too much :)
It appears that `SimpHook` is still not working as one probably expects:
![screenshot from 2016-04-04 22-01-59](https://cloud.githubusercontent.com/assets/10833413/14259722/452c2302-fab9-11e5-8224-c08d1410d8ce.png)
How do I tell Mathematica that I want a unique index `"c"` which cannot appear outside SimpHook?

**Comment by tririver** [comment]
You can make use of `Unique[]`, which is heavily used in `MathGR`:

```
SimpHook := {F[DN[a_], DN[b_]] :> 
   With[{c = Unique[]}, A[DN[a], DN[c]] B[DN[b], UP[c]]]}

Simp[F[DN["a"], DN["b"]]]

Simp[F[DN["a"], DN["b"]] F[DN["c"], DN["d"]]]
```

PS: It would be nicer of you if you can post your questions in plain text instead of screen cast. I have to type the code in your question myself otherwise.
