### ISSUE TITLE
Ibp not working

### ISSUE THREAD

**Issue by s32owl003** [tririver/MathGR#5]
Hi,

I tried to use Ibp as in the manual paper, but I can't get the same result:

![2016-12-06 21 16 43](https://cloud.githubusercontent.com/assets/24420246/20944254/97ee7e02-bbfa-11e6-97ca-e6cb61ddda37.png)

**Comment by tririver** [comment]
Thank you for the but report and sorry for the inconvenience! Indeed I have updated the behavior of Ibp but forgot to update the manual on ArXiv. Now we should write

    Ibp[y Pd[x, DN["i"]], "Rank" -> IbpVar[x]]

    Ibp[f x Pd[x, DE[0]], "Rank" -> IbpStd2]

The ArXiv documentation is now updated (need a day to appear).

**Comment by s32owl003** [comment]
Thank you very much for your reply.
