### ISSUE TITLE
AntiSym does not work as expected

### ISSUE THREAD

**Issue by s32owl003** [tririver/MathGR#6]
Hi,

I found that if I change the sequence of the second argument in AntiSym, the result may not be the same:
![mathgr_20170131_1](https://cloud.githubusercontent.com/assets/24420246/22485250/d5c3c6be-e7fc-11e6-946a-1aec3b41bb2e.png)

However I think the second argument is only indicating which indices have to be permuted, and the result should not be affected by the order. Would some modification like this be better?

![mathgr_20170131_2](https://cloud.githubusercontent.com/assets/24420246/22485450/a90a57e0-e7fd-11e6-8b77-15032b0fc2d3.png)

**Comment by tririver** [comment]
Thanks! Nice finding. I agree about the issue. Will read your modification.

**Comment by tririver** [comment]
I have pushed this change to Master. Thanks again for raising the issue!
